# Programming language install, run, and test commands.

[quickstart_guide]
default = ["echo 'INSERT-INSTALL-COMMANDS'", "echo 'INSERT-RUN-COMMANDS'", "echo 'INSERT-TEST-COMMANDS'"]
C = ["gcc -o myapp main.c", "./myapp", "/* No common unit test framework in C */"]
CPP = ["g++ -o myapp main.cpp", "./myapp", "googletest"]
CSharp = ["dotnet build", "dotnet run", "dotnet test"]
CoffeeScript = ["npm install", "coffee main.coffee", "npm test"]
Crystal = ["shards install", "./main", "crystal spec"]
D = ["dmd main.d", "./main", "rdmd -main -unittest main.d"]
Dart = ["pub get", "dart main.dart", "dart test"]
Delphi = ["dcc32 main.dpr", "main.exe", "Insert test command."]
Elixir = ["mix deps.get", "mix run", "mix test"]
FS = ["dotnet build", "dotnet run", "dotnet test"]
Go = ["go build -o myapp", "./myapp", "go test"]
Groovy = ["grape install", "groovy main.groovy", "Insert test command."]
Haskell = ["ghc -o myapp main.hs", "./myapp", "Insert test command."]
Java = ["mvn clean install", "java -jar target/myapp.jar", "mvn test"]
JavaScript = ["npm install", "node app.js", "npm test"]
Julia = ["julia --project -e 'import Pkg; Pkg.instantiate()'", "julia main.jl", "julia -e 'import Pkg; Pkg.test()'"]
JupyterNotebook = ["pip install -r requirements.txt", "jupyter nbconvert --execute notebook.ipynb", "pytest notebook_test.py"]
Kotlin = ["gradle build", "java -jar build/libs/myapp.jar", "gradle test"]
Lua = ["luarocks install --only-deps myapp", "lua main.lua", "Insert test command."]
MATLAB = ["matlab -r main.m", "matlab -batch 'runtests'"]
ObjectiveC = ["gcc -framework Foundation main.m -o myapp", "./myapp", "Insert test command."]
ObjectScript = ["zpm install", "do ##class(User.MyClass).Main()", "do ##class(%UnitTest.Manager).RunTest()"]
Perl = ["cpanm --installdeps .", "perl main.pl", "prove"]
Perl6 = ["zef install .", "perl6 main.p6", "prove6"]
PHP = ["composer install", "php main.php", "vendor/bin/phpunit"]
PowerShell = ["pwsh main.ps1", "pwsh -Command {Invoke-Pester}"]
Prolog = ["swipl -g main -t halt -q main.pl", "Insert test command."]
Python = ["pip install -r requirements.txt", "python main.py", "pytest"]
R = ["Rscript install.R", "Rscript main.R", "Rscript -e 'devtools::test()'"]
Raku = ["zef install .", "raku main.raku", "prove6"]
Ruby = ["bundle install", "ruby main.rb", "rspec"]
Rust = ["cargo build", "cargo run", "cargo test"]
Scala = ["sbt compile", "sbt run", "sbt test"]
Scheme = ["csi -s main.scm", "/* No common unit test framework in Scheme */"]
Shell = ["chmod +x main.sh", "./main.sh", "bats *.bats"]
Streamlit = ["pip install -r requirements.txt", "streamlit run app.py", "pytest"]
Swift = ["swift build", ".build/debug/myapp", "swift test"]
TypeScript = ["npm install", "npm run build && node dist/main.js", "npm test"]
VBScript = ["cscript main.vbs", "/* No common unit test framework in VBScript */"]
VisualBasic = ["dotnet build", "dotnet run", "dotnet test"]
vue = ["npm install", "npm run serve", "npm test"]
Terraform = ["terraform init", "terraform apply", "Insert test command."]
