# README Template: base_py

[md]
head = """\n<div align="center">
<h1 align="center">
<img src="https://raw.githubusercontent.com/PKief/vscode-material-icon-theme/ec559a9f6bfd399b82bb44393651661b08aaf7ba/icons/folder-markdown-open.svg" width="100" />
<br>{}</h1>
\n> <h3 align="center">[ğŸ‘‰ insert-project-summary]</h3>
> <p align="center">
> {}
> </p>
\n</div>\n
\n---
"""

toc = """
\n## ğŸ“¦ Table of Contents

\n- [ğŸ“ Introdcution](#-introdcution)
\n- [ğŸ”® Features](#-features)
\n- [ğŸŒ² Repository Structure](#repository-structure)
\n- [ğŸ§© Modules](#modules)
\n- [ğŸğŸ’¨ Getting Started](#-getting-started)
\n  - [Prerequisites](#prerequisites)
\n  - [Installation](#installation)
\n  - [Running {name}](#running-{name_lower})
\n- [ğŸ—º Roadmap](#-roadmap)
\n- [ğŸ¤ Contributing](#-contributing)
\n- [ğŸªª License](#-license)
\n- [ğŸ“² Contact](#-contact)
\n- [ğŸ™ Acknowledgments](#-acknowledgments)
\n---"""

body = """
\n## ğŸ“ Introduction
\n> [ğŸ‘‰ insert-description]
\n## ğŸ”® Feautres
\n> [ğŸ‘‰ insert-description]
"""

modules = """
\n---
\n<img src="https://raw.githubusercontent.com/PKief/vscode-material-icon-theme/ec559a9f6bfd399b82bb44393651661b08aaf7ba/icons/folder-src-open.svg" width="80" />
\n## ğŸ§© Modules\n
"""
dropdown = """\n<details closed><summary>{}</summary>\n\n{}\n\n</details>"""

tree = """
\n---
\n<img src="https://raw.githubusercontent.com/PKief/vscode-material-icon-theme/ec559a9f6bfd399b82bb44393651661b08aaf7ba/icons/folder-github-open.svg" width="80" />
\n## ğŸŒ² Repository Structure
"""

usage = """\n<hr />\n
## ğŸğŸ’¨ Getting Started
\n### Prerequisites
\nBefore you begin, ensure that you have the following prerequisites installed:

\n> - [ğŸ‘‰ insert-prerequisites-if-needed]

\n### Installation
\n1. Clone the {name} repository:

\n```sh\ngit clone {url} && cd {name}\n```
\n2. Create a new Conda environment and install the required dependencies:
\n```sh\nconda env create -f setup/environment.yaml\nconda activate {name}\n```
\n> 3. [ğŸ‘‰ insert-additional-steps]

\n```sh\n #... \n```
\n### Running {name}
\n```sh\n# ... \n```
\n---

## ğŸ—º Roadmap

> - [X] [ğŸ‘‰ insert-task]
> - [ ] [ğŸ‘‰ insert-task]
> - [ ] [ğŸ‘‰ insert-task]
\n---

## ğŸ¤ Contributing
\n> [ğŸ‘‰ insert-description]
\n---

## ğŸªª License
\n> [ğŸ‘‰ insert-description]
\n---

## ğŸ“² Contact
\n> [ğŸ‘‰ insert-description]
\n---

## ğŸ™ Acknowledgments
\n> [ğŸ‘‰ insert-description]
\n---
"""