# Prompts
[prompts]
code_to_text = """
Could you generate a robust yet succinct summary that captures the essence of this code script:

{}

Aim for a balance between brevity and completeness in your explanation.
"""
intro = """
In a rapidly evolving technological landscape, the {} GitHub project is a beacon of innovation. 

We invite you to explore and unravel the key features of this project. 

The following are summaries of the code scripts that make up this project:
Repository URL: {}
Code Documentation: {}

Kindly provide insights into:
- The use-case and benefit of the projcet or tool. 
- Focus on the user and the value it provides. 

Generate a response paragraph containing no more than 4 sentences. Thank you!
"""

features = """
In a rapidly evolving technological landscape, the {} GitHub project is a beacon of innovation. 

We invite you to explore and unravel the key features of this project. 

The following are summaries of the code scripts that make up this project:
Repository URL: {}
Code Documentation: {}

Kindly provide insights into:
- The user-centered design elements and architecture. 
- The unique features that make this project stand out from the rest.

Please structure each unique feature as a bullet point list. Example Markdown Outline:

### Distinctive Features

1. **<FEATURE-DESCRIPTION>:** 
2. **<FEATURE-DESCRIPTION>:**
3. **<FEATURE-DESCRIPTION>:**
- etc.

---

Your insights will not only enlighten us but will also empower others to understand the project better 
and appreciate its depth and breadth. Thank you!
"""

slogan = """Generate a slogan for the GitHub project: {}"""

# OpenAI API Parameters
[api]
api_key = ""
engine = "text-davinci-003"
tokens = 1024

# Repository (local and remote)
[git]
name = "README-AI"
repository = "https://github.com/eli64s/README-AI"

# Paths
[paths]
dependency_files = "dependency_files.toml"
ignore_files = "ignore_files.toml"
language_names = "language_names.toml"
language_setup = "language_setup.toml"
badges = "conf/badges.json"
md = "README_AI.md"

# Markdown template
[md]
head = """\n<div align="center">
<h1 align="center">
<img src="https://raw.githubusercontent.com/PKief/vscode-material-icon-theme/ec559a9f6bfd399b82bb44393651661b08aaf7ba/icons/folder-markdown-open.svg" width="100" />
<br>
{}
</h1>
<h3 align="center">ğŸ“ {}</h3>
<h3 align="center">ğŸš€ Developed with the software and tools below:</h3>
<p align="center">
\n{}
</p>
\n</div>
\n---
"""

toc = """
## ğŸ“š Table of Contents
- [ğŸ“š Table of Contents](#-table-of-contents)
- [ğŸ“Overview](#-introdcution)
- [ğŸ”® Features](#-features)
- [âš™ï¸ Project Structure](#project-structure)
- [ğŸ§© Modules](#modules)
- [ğŸğŸ’¨ Getting Started](#-getting-started)
- [ğŸ—º Roadmap](#-roadmap)
- [ğŸ¤ Contributing](#-contributing)
- [ğŸªª License](#-license)
- [ğŸ“« Contact](#-contact)
- [ğŸ™ Acknowledgments](#-acknowledgments)
\n---
"""

intro = """
\n## ğŸ“Overview
\n{}
\n---
\n## ğŸ”® Feautres
\n{}
\n---
"""

modules = """
\n---
\n<img src="https://raw.githubusercontent.com/PKief/vscode-material-icon-theme/ec559a9f6bfd399b82bb44393651661b08aaf7ba/icons/folder-src-open.svg" width="80" />
\n## ğŸ’» Modules
"""
dropdown = """<details closed><summary>{}</summary>\n\n{}\n\n</details>\n"""

tree = """
\n<img src="https://raw.githubusercontent.com/PKief/vscode-material-icon-theme/ec559a9f6bfd399b82bb44393651661b08aaf7ba/icons/folder-github-open.svg" width="80" />
\n## âš™ï¸ Project Structure\n
"""

setup = """<hr />
\n## ğŸš€ Getting Started
\n### âœ… Prerequisites
\nBefore you begin, ensure that you have the following prerequisites installed:
> `[ğŸ“Œ  INSERT-PROJECT-PREREQUISITES]`
\n### ğŸ’» Installation
\n1. Clone the {} repository:
```sh\ngit clone {}\n```
\n2. Change to the project directory:
```sh\ncd {}\n```
\n3. Install the dependencies:
```sh\n{}\n```
\n### ğŸ¤– Using {}
\n```sh\n{}\n```
\n### ğŸ§ª Running Tests
```sh\n#run tests\n```
\n<hr />
"""

slogan = "{}"

close = """
\n## ğŸ›  Future Development
- [X] [ğŸ“Œ  COMPLETED-TASK]
- [ ] [ğŸ“Œ  INSERT-TASK]
- [ ] [ğŸ“Œ  INSERT-TASK]

\n---

## ğŸ¤ Contributing
Contributions are always welcome! Please follow these steps:
1. Fork the project repository. This creates a copy of the project on your account that you can modify without affecting the original project.
2. Clone the forked repository to your local machine using a Git client like Git or GitHub Desktop.
3. Create a new branch with a descriptive name (e.g., `new-feature-branch` or `bugfix-issue-123`).
```sh
git checkout -b new-feature-branch
```
4. Make changes to the project's codebase.
5. Commit your changes to your local branch with a clear commit message that explains the changes you've made.
```sh
git commit -m 'Implemented new feature.'
```
6. Push your changes to your forked repository on GitHub using the following command
```sh
git push origin new-feature-branch
```
7. Create a pull request to the original repository.
Open a new pull request to the original project repository. In the pull request, describe the changes you've made and why they're necessary.
The project maintainers will review your changes and provide feedback or merge them into the main branch.
\n---

## ğŸªª License

This project is licensed under the `[ğŸ“Œ  INSERT-LICENSE-TYPE]` License. See the [LICENSE](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) file for additional info.
\n---

## ğŸ™ Acknowledgments

[ğŸ“Œ  INSERT-DESCRIPTION]

\n---\n
"""
