# OpenAI API Settings
[api]
endpoint = "https://api.openai.com/v1/chat/completions"
engine = "gpt-3.5-turbo"
encoding = "cl100k_base"
rate_limit = 5
tokens = 699
tokens_max = 4000
temperature = 0.9

# Repository
[git]
name = "readme-ai"
repository = "https://github.com/eli64s/readme-ai"

# Paths
[paths]
badges = "conf/svg/badges_compressed.json"
dependency_files = "dependency_files.toml"
ignore_files = "ignore_files.toml"
language_names = "language_names.toml"
language_setup = "language_setup.toml"
readme = "readme_ai.md"

# Prompts
[prompts]
code_summary = """Offer a comprehensive summary that encapsulates the core functionalities of the provided code snippet:
\n{}\n
Aim for precision and conciseness in your explanation, ensuring a fine balance between detail and brevity.
Limit your response to a maximum of 350 characters (including spaces).
"""
features = """Hello! Please analyze the codebase located at {} and provide a list of important features. The following includes a list of the summaries of the files in the repository:
\n{}\n
Please consider the codebase as a whole and highlight its key characteristics, design patterns, architectural decisions, and any other noteworthy elements.
Generate your response as a Markdown table with the following columns:

| Feature                | Description                           |
| ---------------------- | ------------------------------------- |
| **âš™ï¸ Architecture**    | Analyze the structural design of the system here. Limit your response to a maximum of 275 characters (including spaces).    |
| **ğŸ“– Documentation**   | Discuss the quality and comprehensiveness of the documentation here. Limit your response to a maximum of 275 characters (including spaces).    |
| **ğŸ”— Dependencies**    | Examine the external libraries or other systems that this system relies on here. Limit your response to a maximum of 275 characters (including spaces).    |
| **ğŸ§© Modularity**      | Discuss the system's organization into smaller, interchangeable components here. Limit your response to a maximum of 275 characters (including spaces).    |
| **âœ”ï¸ Testing**         | Evaluate the system's testing strategies and tools here. Limit your response to a maximum of 275 characters (including spaces).    |
| **âš¡ï¸ Performance**     | 	Analyze how well the system performs, considering speed, efficiency, and resource usage here. Limit your response to a maximum of 275 characters (including spaces).    |
| **ğŸ” Security**        | Assess the measures the system uses to protect data and maintain functionality here. Limit your response to a maximum of 275 characters (including spaces).    |
| **ğŸ”€ Version Control** | Discuss the system's version control strategies and tools here. Limit your response to a maximum of 275 characters (including spaces).    |
| **ğŸ”Œ Integrations**    | Evaluate how the system interacts with other systems and services here. Limit your response to a maximum of 275 characters (including spaces).    |
| **ğŸ“¶ Scalability**     | Analyze the system's ability to handle growth here. Limit your response to a maximum of 275 characters (including spaces).    |

Please provide a comprehensive technical analysis of the codebase and its components.
"""
overview = """Please analyze the codebase located at {} and provide a robust, yet succinct overview of the rpoject.
The following includes a list of the summaries of the files in the repository:
\n{}\n
Craft 3-4 sentences that encapsulate the core functionalities of the project, its purpose, and its value proposition.
"""
slogan = "Conceptualize a catchy and memorable slogan for the GitHub project: {}. Limit your response to 80 characters."

# Markdown Templates
[md]
default = "`â„¹ï¸  INSERT-DESCRIPTION`"
dropdown = """<details closed><summary>{}</summary>\n\n{}\n\n</details>\n"""
header = """\n<div align="center">
<h1 align="center">
<img src="https://raw.githubusercontent.com/PKief/vscode-material-icon-theme/ec559a9f6bfd399b82bb44393651661b08aaf7ba/icons/folder-markdown-open.svg" width="100" />
<br>
{}
</h1>
<h3>â—¦ {}</h3>
<h3>â—¦ Developed with the software and tools listed below.</h3>
"""
badges = """<p align="center">
{0}
</p>
\n![GitHub top language](https://img.shields.io/github/languages/top/{1}?style&color=5D6D7E)
![GitHub code size in bytes](https://img.shields.io/github/languages/code-size/{1}?style&color=5D6D7E)
![GitHub commit activity](https://img.shields.io/github/commit-activity/m/{1}?style&color=5D6D7E)
![GitHub license](https://img.shields.io/github/license/{1}?style&color=5D6D7E)
</div>
\n---
"""
toc = """
## ğŸ“’ Table of Contents
- [ğŸ“’ Table of Contents](#-table-of-contents)
- [ğŸ“ Overview](#-overview)
- [âš™ï¸ Features](#-features)
- [ğŸ“‚ Project Structure](#project-structure)
- [ğŸ§© Modules](#modules)
- [ğŸš€ Getting Started](#-getting-started)
- [ğŸ—º Roadmap](#-roadmap)
- [ğŸ¤ Contributing](#-contributing)
- [ğŸ“„ License](#-license)
- [ğŸ‘ Acknowledgments](#-acknowledgments)
\n---
"""
intro = """
\n## ğŸ“ Overview
\n{}
\n---
\n## âš™ï¸ Features
\n{}
\n---
"""
# \n<img src="https://raw.githubusercontent.com/PKief/vscode-material-icon-theme/ec559a9f6bfd399b82bb44393651661b08aaf7ba/icons/folder-github-open.svg" width="80" />
tree = """
\n## ğŸ“‚ Project Structure\n
"""
# \n<img src="https://raw.githubusercontent.com/PKief/vscode-material-icon-theme/ec559a9f6bfd399b82bb44393651661b08aaf7ba/icons/folder-src-open.svg" width="80" />
modules = """
\n---
\n## ğŸ§© Modules
"""
setup = """---
\n## ğŸš€ Getting Started
\n### âœ”ï¸ Prerequisites
\nBefore you begin, ensure that you have the following prerequisites installed:
> - `â„¹ï¸ Requirement 1`
> - `â„¹ï¸ Requirement 2`
> - `â„¹ï¸ ...`
\n### ğŸ’» Installation
\n1. Clone the {0} repository:
```sh\ngit clone {1}\n```
\n2. Change to the project directory:
```sh\ncd {0}\n```
\n3. Install the dependencies:
```sh\n{2}\n```
\n### ğŸ® Using {0}
\n```sh\n{3}\n```
\n### ğŸ§ª Running Tests
```sh\n{4}\n```
\n---
"""
ending = """
\n## ğŸ—º Roadmap

> - [X] `â„¹ï¸  Task 1: Implement X`
> - [ ] `â„¹ï¸  Task 2: Refactor Y`
> - [ ] `â„¹ï¸ ...`

\n---

## ğŸ¤ Contributing

Contributions are always welcome! Please follow these steps:
1. Fork the project repository. This creates a copy of the project on your account that you can modify without affecting the original project.
2. Clone the forked repository to your local machine using a Git client like Git or GitHub Desktop.
3. Create a new branch with a descriptive name (e.g., `new-feature-branch` or `bugfix-issue-123`).
```sh
git checkout -b new-feature-branch
```
4. Make changes to the project's codebase.
5. Commit your changes to your local branch with a clear commit message that explains the changes you've made.
```sh
git commit -m 'Implemented new feature.'
```
6. Push your changes to your forked repository on GitHub using the following command
```sh
git push origin new-feature-branch
```
7. Create a new pull request to the original project repository. In the pull request, describe the changes you've made and why they're necessary.
The project maintainers will review your changes and provide feedback or merge them into the main branch.

---

## ğŸ“„ License

This project is licensed under the `â„¹ï¸  INSERT-LICENSE-TYPE` License. See the [LICENSE](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) file for additional info.

---

## ğŸ‘ Acknowledgments

> - `â„¹ï¸  List any resources, contributors, inspiration, etc.`

---
"""
