# OpenAI API Settings
[api]
endpoint = "https://api.openai.com/v1/chat/completions"
engine = "gpt-3.5-turbo"
encoding = "cl100k_base"
rate_limit = 5
tokens = 600
tokens_max = 4000
temperature = 0.9

# Repository
[git]
name = "readme-ai"
repository = "https://github.com/eli64s/readme-ai"

# Paths
[paths]
badges = "conf/svg/badges_compressed.json"
dependency_files = "dependency_files.toml"
ignore_files = "ignore_files.toml"
language_names = "language_names.toml"
language_setup = "language_setup.toml"
readme = "readme_ai.md"

# Prompts
[prompts]
code_summary = """Offer a comprehensive summary that encapsulates the core functionalities of the provided code snippet:
\n{}\n
Aim for precision and conciseness in your explanation, ensuring a fine balance between detail and brevity.
Limit your response to 3-4 sentences.
Thank you!
"""
features = """Hello! Please analyze the codebase located at {} and provide a list of important features. The following includes a list of the summaries of the files in the repository:
\n{}\n
Please consider the codebase as a whole and highlight its key characteristics, design patterns, architectural decisions, and any other noteworthy elements.
Generate your response as a Markdown table with the following columns:

| Feature | Description |
| ----- | ----- |
| **ğŸ— Architecture** | Place a 1-3 sentence analysis here. |
| **ğŸ“‘ Documentation** | Place a 1-3 sentence analysis here. |
| **ğŸ§© Dependencies** | Place a 1-3 sentence analysis here. |
| **â™»ï¸ Modularity** | Place a 1-3 sentence analysis here. |
| **âœ”ï¸ Testing** | Place a 1-3 sentence analysis here. |
| **âš¡ï¸ Performance** | Place a 1-3 sentence analysis here. |
| **ğŸ”’ Security** | Place a 1-3 sentence analysis here. |
| **ğŸ”€ Version Control** | Place a 1-3 sentence analysis here. |
| **ğŸ”Œ Integrations** | Place a 1-3 sentence analysis here. |
| **ğŸ“ˆ Scalability** | Place a 1-3 sentence analysis here. |

Please provide a comprehensive analysis addressing the above features while excluding the specified files from the assessment.
Thank you!
"""
overview = """Please analyze the codebase located at {} and provide a robust, yet succinct overview of the rpoject.
The following includes a list of the summaries of the files in the repository:
\n{}\n
Craft 3-4 sentences that encapsulate the core functionalities of the project, its purpose, and its value proposition.
"""
slogan = "Conceptualize a catchy and memorable slogan for the GitHub project: {}. Limit your response to 80 characters."
# Markdown Templates
[md]
default = "[â„¹ï¸  INSERT-DESCRIPTION]"
dropdown = """<details closed><summary>{}</summary>\n\n{}\n\n</details>\n"""
header = """\n<div align="center">
<h1 align="center">
<img src="https://raw.githubusercontent.com/PKief/vscode-material-icon-theme/ec559a9f6bfd399b82bb44393651661b08aaf7ba/icons/folder-markdown-open.svg" width="100" />
<br>
{}
</h1>
<h3>â—¦ {}</h3>
<h3>â—¦ Developed with the software and tools listed below.</h3>
"""
badges = """<p align="center">
{}
</p>
</div>
\n---
"""
toc = """
## ğŸ“š Table of Contents
- [ğŸ“š Table of Contents](#-table-of-contents)
- [ğŸ“ Overview](#-overview)
- [âš™ï¸ Features](#-features)
- [ğŸ“‚ Project Structure](#project-structure)
- [ğŸ§© Modules](#modules)
- [ğŸš€ Getting Started](#-getting-started)
- [ğŸ—º Roadmap](#-roadmap)
- [ğŸ¤ Contributing](#-contributing)
- [ğŸ“„ License](#-license)
- [ğŸ‘ Acknowledgments](#-acknowledgments)
\n---
"""
intro = """
\n## ğŸ“ Overview
\n{}
\n---
\n## âš™ï¸ Features
\n{}
\n---
"""
# \n<img src="https://raw.githubusercontent.com/PKief/vscode-material-icon-theme/ec559a9f6bfd399b82bb44393651661b08aaf7ba/icons/folder-github-open.svg" width="80" />
tree = """
\n## ğŸ“‚ Project Structure\n
"""
# \n<img src="https://raw.githubusercontent.com/PKief/vscode-material-icon-theme/ec559a9f6bfd399b82bb44393651661b08aaf7ba/icons/folder-src-open.svg" width="80" />
modules = """
\n---
\n## ğŸ§© Modules
"""
setup = """---
\n## ğŸš€ Getting Started
\n### âœ… Prerequisites
\nBefore you begin, ensure that you have the following prerequisites installed:
> - [â„¹ï¸ Requirement 1]
> - [â„¹ï¸ Requirement 2]
> - [...]
\n### ğŸ–¥ Installation
\n1. Clone the {0} repository:
```sh\ngit clone {1}\n```
\n2. Change to the project directory:
```sh\ncd {0}\n```
\n3. Install the dependencies:
```sh\n{2}\n```
\n### ğŸ¤– Using {0}
\n```sh\n{3}\n```
\n### ğŸ§ª Running Tests
```sh\n{4}\n```
\n---
"""
ending = """
\n## ğŸ—º Roadmap

> - [X] [â„¹ï¸  Task 1: Implement X]
> - [ ] [â„¹ï¸  Task 2: Refactor Y]
> - [ ] [...]

\n---

## ğŸ¤ Contributing

Contributions are always welcome! Please follow these steps:
1. Fork the project repository. This creates a copy of the project on your account that you can modify without affecting the original project.
2. Clone the forked repository to your local machine using a Git client like Git or GitHub Desktop.
3. Create a new branch with a descriptive name (e.g., `new-feature-branch` or `bugfix-issue-123`).
```sh
git checkout -b new-feature-branch
```
4. Make changes to the project's codebase.
5. Commit your changes to your local branch with a clear commit message that explains the changes you've made.
```sh
git commit -m 'Implemented new feature.'
```
6. Push your changes to your forked repository on GitHub using the following command
```sh
git push origin new-feature-branch
```
7. Create a new pull request to the original project repository. In the pull request, describe the changes you've made and why they're necessary.
The project maintainers will review your changes and provide feedback or merge them into the main branch.

---

## ğŸ“„ License

This project is licensed under the `[â„¹ï¸  INSERT-LICENSE-TYPE]` License. See the [LICENSE](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) file for additional info.

---

## ğŸ‘ Acknowledgments

> - [â„¹ï¸  List any resources, contributors, inspiration, etc.]

---
"""
