# Map file extensions to programming languages.

[extensions]
    ".asm" = "Assembly"
    ".c" = "C"
    ".cfg" = "CFG"
    ".cfg.lua" = "LÃ–VE2D"
    ".cmake" = "CMake"
    ".coffee" = "CoffeeScript"
    ".cpp" = "C++"
    ".cs" = "C#"
    ".csproj" = "XML"
    ".dart" = "Dart"
    ".fs" = "F#"
    ".fsi" = "F#"
    ".go" = "Go"
    ".groovy" = "Groovy"
    ".h" = "C"
    ".hpp" = "C++"
    ".hs" = "Haskell"
    ".html" = "HTML"
    ".ipynb" = "Jupyter Notebook"
    ".java" = "Java"
    ".jl" = "Julia"
    ".js" = "JavaScript"
    ".json" = "JSON"
    ".kt" = "Kotlin"
    ".lua" = "Lua"
    ".m" = "Objective-C"
    ".md" = "Markdown"
    ".mm" = "Objective-C++"
    ".php" = "PHP"
    ".pl" = "Perl"
    ".ps1" = "PowerShell"
    ".psm1" = "PowerShell"
    ".py" = "Python"
    ".r" = "R"
    ".rb" = "Ruby"
    ".rs" = "Rust"
    ".rst" = "reStructuredText"
    ".s" = "Assembly"
    ".scala" = "Scala"
    ".sh" = "Shell"
    ".sql" = "SQL"
    ".svg" = "SVG"
    ".swift" = "Swift"
    ".swiftdeps" = "Swift"
    ".tex" = "TeX"
    ".toml" = "TOML"
    ".ts" = "TypeScript"
    ".tsx" = "TypeScript"
    ".txt" = "Text"
    ".v" = "Verilog"
    ".vh" = "Verilog"
    ".xml" = "XML"
    ".yaml" = "YAML"
    ".yml" = "YAML"