# Files to ignore when parsing repository contents.

[ignore_files]
directories = [
    ".DS_Store",
    ".dvc",
    ".eggs",
    ".git",
    ".hg",
    ".pytest_cache",
    ".svn",
    ".tox",
    ".vscode",
    "assets",
    "data",
    "dist",
    "docs",
    "htmlcov",
    "imgs",
    "lock",
    "media",
    "static",
    "tests",
    "testing",
    "tools",
    "__pycache__",
    ".idea",
]
extensions = [
    ".iml",
    ".lock",
    ".cache",
    ".cfg",
    ".cert",
    ".class",
    ".config",
    ".coverage",
    ".csv",
    ".docx",
    ".egg-info",
    ".env",
    ".env.example",
    ".env.local",
    ".env.production",
    ".env.test",
    ".gif",
    ".h5",
    ".ini",
    ".jpg",
    ".json",
    ".jsonl",
    ".json5",
    ".key",
    ".md",
    ".mp4",
    ".o",
    ".p12",
    ".pdf",
    ".pem",
    ".pickle",
    ".pkl",
    ".properties",
    ".pyc",
    ".pyo",
    ".sav",
    ".secret",
    ".sublime-*",
    ".sum",
    ".swp",
    ".toml",
    ".tsv",
    ".txt",
    ".xml",
    ".yaml",
    ".yml",
    ".zip",
    ".xlsx",
    ".xls",
    ".exe",
    ".dll",
    ".bak",
    ".bakup",
    ".old",
    ".tmp",
    ".png",
    ".jpeg",
    ".bmp",
    ".svg",
    ".ico",
    ".webp",
    ".tiff",
    ".nsi",
    ".nsh",
    ".pub",
    ".sig",
    ".gz",
    ".gitignore",
    ".icns",
    ".DS_Store",
    ".jar",
    ".pro",
    ".apk",
    ".sample",
]
files = [
    "AUTHORS",
    "CHANGELOG",
    "toml",
    "init.py",
    "__init__.py",
    ".babelrc",
    ".editorconfig",
    "test_binary",
    "icon.ico~dev",
    ".env",
    ".env.example",
    ".env.local",
    ".env.production",
    ".env.test",
    ".project-root",
    ".gitattributes",
    ".gitkeep",
    ".gitmodules",
    ".gitlab-ci.yml",
    ".dvcignore",
    ".flake8",
    ".gitignore",
    ".npmignore",
    "appimage",
    "badges.json",
    "bundle_dmg",
    "CHANGELOG",
    "CODE_OF_CONDUCT.md",
    "CONTRIBUTING.md",
    "LICENSE",
    "LICENSE-MIT",
    "LICENSE-APACHE",
    "LICENSE_APACHE-2.0",
    "MANIFEST",
    "README.md",
    ".dockerignore",
    "start",
    "gradlew",
    ".DS_Store",
    ".gitignore",
    ".whitesource",
    ".prettierrc",
]