# OpenAI API Settings
[api]
endpoint = "https://api.openai.com/v1/chat/completions"
engine = "gpt-3.5-turbo"
encoding = "cl100k_base"
rate_limit = 5
tokens = 650
tokens_max = 3800
temperature = 1.2

# Repository
[git]
repository = "https://github.com/eli64s/readme-ai"
name = "readme-ai"

# Paths
[paths]
badges = "conf/badges.json"
dependency_files = "dependency_files.toml"
ignore_files = "ignore_files.toml"
language_names = "language_names.toml"
language_setup = "language_setup.toml"
readme = "readme-ai.md"

# Prompts
[prompts]
code_summary = """Offer a comprehensive summary that encapsulates the core functionalities of the code:
\n{}\n Aim for precision and conciseness in your explanation, ensuring a fine balance between detail and brevity.
Limit your response to a maximum of 350 characters (including spaces).
"""
features = """Hello! Analyze the Git codebase {} and create a robust summary of the project's features.
The following information summarizes each file in the repository to help you get started: \n{}\n
Please provide a comprehensive technical analysis of the codebase and its components.
Consider the codebase as a whole and highlight the key characteristics, design patterns, architectural decisions, and any other noteworthy elements.
Generate your response as a Markdown table with the following columns:

|    | Feature            | Description                                                                                                        |
|----|--------------------|--------------------------------------------------------------------------------------------------------------------|
| ‚öôÔ∏è | **Architecture**   | Analyze the structural design of the system here. Limit your response to a maximum of 200 characters.             |
| üìÑ | **Documentation**  | Discuss the quality and comprehensiveness of the documentation here. Limit your response to a maximum of 200 characters.|
| üîó | **Dependencies**   | Examine the external libraries or other systems that this system relies on here. Limit your response to a maximum of 200 characters.|
| üß© | **Modularity**     | Discuss the system's organization into smaller, interchangeable components here. Limit your response to a maximum of 200 characters.|
| üß™ | **Testing**        | Evaluate the system's testing strategies and tools here. Limit your response to a maximum of 200 characters.       |
| ‚ö°Ô∏è | **Performance**    | Analyze how well the system performs, considering speed, efficiency, and resource usage here. Limit your response to a maximum of 200 characters.|
| üîê | **Security**       | Assess the measures the system uses to protect data and maintain functionality here. Limit your response to a maximum of 200 characters.|
| üîÄ | **Version Control**| Discuss the system's version control strategies and tools here. Limit your response to a maximum of 200 characters.|
| üîå | **Integrations**   | Evaluate how the system interacts with other systems and services here. Limit your response to a maximum of 200 characters.|
| üì∂ | **Scalability**    | Analyze the system's ability to handle growth here. Limit your response to a maximum of 200 characters.           |

Thank you for your time and effort!
"""
overview = """Please analyze the codebase located at {} and provide a robust, yet succinct overview of the rpoject.
The following includes a list of the summaries of the files in the repository: \n{}\n
Craft 3-4 sentences that encapsulate the core functionalities of the project, its purpose, and its value proposition.
"""
slogan = "Conceptualize a catchy and memorable slogan for the GitHub project: {}. Limit your response to 80 characters."

# Markdown Templates
[md]
default = "`‚ÑπÔ∏è  INSERT-DESCRIPTION`"
dropdown = """<details closed><summary>{}</summary>\n\n{}\n\n</details>\n"""
header = """<div align="center">
<h1 align="center">
<img src="https://raw.githubusercontent.com/PKief/vscode-material-icon-theme/ec559a9f6bfd399b82bb44393651661b08aaf7ba/icons/folder-markdown-open.svg" width="100" />
<br>{}
</h1>
<h3>‚ó¶ {}</h3>
<h3>‚ó¶ Developed with the software and tools below.</h3>
"""
badges = """<p align="center">
{0}
</p>
<img src="https://img.shields.io/github/languages/top/{1}?style&color=5D6D7E" alt="GitHub top language" />
<img src="https://img.shields.io/github/languages/code-size/{1}?style&color=5D6D7E" alt="GitHub code size in bytes" />
<img src="https://img.shields.io/github/commit-activity/m/{1}?style&color=5D6D7E" alt="GitHub commit activity" />
<img src="https://img.shields.io/github/license/{1}?style&color=5D6D7E" alt="GitHub license" />
</div>
\n---
"""
toc = """
## üìñ Table of Contents
- [üìñ Table of Contents](#-table-of-contents)
- [üìç Overview](#-overview)
- [üì¶ Features](#-features)
- [üìÇ Repository Structure](#-repository-structure)
- [‚öôÔ∏è Modules](#modules)
- [üöÄ Getting Started](#-getting-started)
    - [üîß Installation](#-installation)
    - [ü§ñ Running {0}](#-running-{0})
    - [üß™ Tests](#-tests)
- [üõ£ Roadmap](#-roadmap)
- [ü§ù Contributing](#-contributing)
- [üìÑ License](#-license)
- [üëè Acknowledgments](#-acknowledgments)
\n---
"""
intro = """
\n## üìç Overview
\n{}
\n---
\n## üì¶ Features
\n{}
\n---
"""
tree = """
\n## üìÇ Repository Structure\n
"""
modules = """
\n---
\n## ‚öôÔ∏è Modules
"""
setup = """---
\n## üöÄ Getting Started

***Dependencies***

Please ensure you have the following dependencies installed on your system:
\n`- ‚ÑπÔ∏è Dependency 1`
\n`- ‚ÑπÔ∏è Dependency 2`
\n`- ‚ÑπÔ∏è ...`

### üîß Installation
\n1. Clone the {0} repository:
```sh\ngit clone {1}\n```
\n2. Change to the project directory:
```sh\ncd {0}\n```
\n3. Install the dependencies:
```sh\n{2}\n```

### ü§ñ Running {0}
\n```sh\n{3}\n```

### üß™ Tests
```sh\n{4}\n```
\n---
"""
ending = """
\n## üõ£ Roadmap

> - [X] `‚ÑπÔ∏è  Task 1: Implement X`
> - [ ] `‚ÑπÔ∏è  Task 2: Implement Y`
> - [ ] `‚ÑπÔ∏è ...`

\n---

## ü§ù Contributing

Contributions are always welcome! Please follow these steps:
1. Fork the project repository. This creates a copy of the project on your account that you can modify without affecting the original project.
2. Clone the forked repository to your local machine using a Git client like Git or GitHub Desktop.
3. Create a new branch with a descriptive name (e.g., `new-feature-branch` or `bugfix-issue-123`).
```sh
git checkout -b new-feature-branch
```
4. Make changes to the project's codebase.
5. Commit your changes to your local branch with a clear commit message that explains the changes you've made.
```sh
git commit -m 'Implemented new feature.'
```
6. Push your changes to your forked repository on GitHub using the following command
```sh
git push origin new-feature-branch
```
7. Create a new pull request to the original project repository. In the pull request, describe the changes you've made and why they're necessary.
The project maintainers will review your changes and provide feedback or merge them into the main branch.

---

## üìÑ License

This project is licensed under the `‚ÑπÔ∏è  LICENSE-TYPE` License. See the [LICENSE-Type](LICENSE) file for additional info.

---

## üëè Acknowledgments

`- ‚ÑπÔ∏è List any resources, contributors, inspiration, etc.`

---
"""
