# CLI Options
[cli]
emojis = false
offline = false

# File Resources
[files]
dependency_files = "dependency_files.toml"
identifiers = "identifiers.toml"
ignore_files = "ignore_files.toml"
language_names = "language_names.toml"
language_setup = "language_setup.toml"
output = "readme-ai.md"
shieldsio_icons = "data/shieldsio.json"
skill_icons = "data/skill_icons.json"

# Git Options
[git]
repository = "https://github.com/eli64s/readme-ai"

# Language Model API Settings
[llm]
endpoint = "https://api.openai.com/v1/chat/completions"
encoding = "cl100k_base"
model = "gpt-3.5-turbo"
rate_limit = 5
temperature = 1.0
tokens = 699
tokens_max = 3999

# Markdown Templates
[md]
align = "center"
default = "`‚ñ∫ INSERT-TEXT`"
dropdown = """<details closed><summary>{}</summary>\n\n{}\n\n</details>\n"""
image = ""
tables = ""

header = """<div align="{0}">
<h1><img src={1} width="100" />
<br>{2}</h1>
<h3>‚ó¶ {3}</h3>
<h3>‚ó¶ Developed with the software and tools below.</h3>
"""
header_left = """[<img src={0} height="120" align="left">]({0})
# {1}
### {2}\n
"""

badges_offline = """<p align="{0}">
{1}
</p>
</div>
<hr>
"""
badges_shieldsio = """<p align="{0}">
{1}
</p>
<img src="https://img.shields.io/github/license/{2}?style={3}&color=5D6D7E" alt="GitHub license" />
<img src="https://img.shields.io/github/last-commit/{2}?style={3}&color=5D6D7E" alt="git-last-commit" />
<img src="https://img.shields.io/github/commit-activity/m/{2}?style={3}&color=5D6D7E" alt="GitHub commit activity" />
<img src="https://img.shields.io/github/languages/top/{2}?style={3}&color=5D6D7E" alt="GitHub top language" />
</div>
<hr>
"""
badges_skills = """
<div align="{0}">
<h1><img src={1} width="100" />
<br>{2}</h1>
<h3>‚ó¶ {3}</h3>
<h3>‚ó¶ Developed with the software and tools below.</h3>
</div>
<p align="{4}">
<a href="https://skillicons.dev">
<img src="{5}">
</a>
</p>
<hr>
"""
badges_style="flat"

toc = """
## üîó Quick Links
- [üîó Quick Links](#-quick-links)
- [üìç Overview](#-overview)
- [üì¶ Features](#-features)
- [üìÇ Repository Structure](#-repository-structure)
- [üß© Modules](#modules)
- [üöÄ Getting Started](#-getting-started)
    - [‚öôÔ∏è Installation](#-installation)
    - [ü§ñ Running {0}](#-running-{0})
    - [üß™ Tests](#-tests)
- [üöß Roadmap](#-roadmap)
- [ü§ù Contributing](#-contributing)
- [üìÑ License](#-license)
- [üëè Acknowledgments](#-acknowledgments)

---
"""

intro = """

## üìç Overview

{}

---

## üì¶ Features

{}

---
"""

tree = """

## üìÇ Repository Structure

```sh
{0}
```

---
"""

modules = """
\n## üß© Modules
"""
setup = """---

## üöÄ Getting Started

***Prerequisites***

Ensure you have the following dependencies installed on your system:

- `‚ñ∫ INSERT-DEPENDENCY-1`
- `‚ñ∫ INSERT-DEPENDENCY-2`
- `‚ñ∫ INSERT-DEPENDENCY-3`

### ‚öôÔ∏è Installation

1. Clone the {0} repository:
```sh
git clone {1}
```

2. Change to the project directory:
```sh
cd {0}
```

3. Install the dependencies:
```sh
{2}
```

### ü§ñ Running {0}
\n```sh\n{3}\n```

### üß™ Tests
```sh\n{4}\n```
\n---
"""

contribute = """
\n## üöß Project Roadmap

> - [X] `‚ÑπÔ∏è  Task 1: Implement X`
> - [ ] `‚ÑπÔ∏è  Task 2: Implement Y`
> - [ ] `‚ÑπÔ∏è ...`

\n---

## ü§ù Contributing

Contributions are welcome! Here are several ways you can contribute:

- **[Submit Pull Requests](https://github.com/{0}/blob/main/CONTRIBUTING.md)**: Review open PRs, and submit your own PRs.
- **[Join the Discussions](https://github.com/{0}/discussions)**: Share your insights, provide feedback, or ask questions.
- **[Report Issues](https://github.com/{0}/issues)**: Submit bugs found or log feature requests for {1}.

#### *Contributing Guidelines*

<details closed>
<summary>Click to expand</summary>

1. **Fork the Repository**: Start by forking the project repository to your GitHub account.
2. **Clone Locally**: Clone the forked repository to your local machine using a Git client.
   ```sh
   git clone <your-forked-repo-url>
   ```
3. **Create a New Branch**: Always work on a new branch, giving it a descriptive name.
   ```sh
   git checkout -b new-feature-x
   ```
4. **Make Your Changes**: Develop and test your changes locally.
5. **Commit Your Changes**: Commit with a clear and concise message describing your updates.
   ```sh
   git commit -m 'Implemented new feature x.'
   ```
6. **Push to GitHub**: Push the changes to your forked repository.
   ```sh
   git push origin new-feature-x
   ```
7. **Submit a Pull Request**: Create a PR against the original project repository. Clearly describe the changes and their motivations.

Once your PR is reviewed and approved, it will be merged into the main branch.

</details>

---

## üìÑ License


This project is protected under the [SELECT-A-LICENSE](https://choosealicense.com/licenses) License. For more details, refer to the [LICENSE](https://choosealicense.com/licenses/) file.

---

## üëè Acknowledgments

- List any resources, contributors, inspiration, etc. here.

[**Return**](#-quick-links)

---
"""

# Language Model Prompts
[prompts]
features = """Hello! Please analyze the repository {0} and provide a comprehensive technical analysis of its codebase and components. \
Generate your response as a formatted Markdown table using the template below.\n

Markdown Template:

| Symbol | Feature             | Description                                                                                                            |
|--------|---------------------|------------------------------------------------------------------------------------------------------------------------|
| ‚öôÔ∏è     | **Architecture**    | Analyze and describe the repository's structural design, focusing on its layout and framework.                         |
| üìÑ     | **Documentation**   | Evaluate the documentation's quality and depth, noting its clarity and thoroughness.                                    |
| üîó     | **Dependencies**    | Identify and discuss the external libraries or systems the repository depends upon.                                     |
| üß©     | **Modularity**      | Assess how the repository is divided into smaller, interchangeable parts or modules.                                   |
| üß™     | **Testing**         | Examine the testing methodologies and tools employed in the repository.                                                |
| ‚ö°Ô∏è     | **Performance**     | Analyze the repository's performance, considering aspects like speed, efficiency, and resource utilization.            |
| üîê     | **Security**        | Review the security measures in place for data protection and maintaining functionality.                               |
| üîÄ     | **Version Control** | Discuss the strategies and tools used for version control in the repository.                                           |
| üîå     | **Integrations**    | Evaluate how the repository integrates with other systems and services.                                                |
| üì∂     | **Scalability**     | Analyze the repository's capability to accommodate growth and handle scaling challenges.                               |

Adhering to the table structure and 40-token limit for each feature description is essential.

Token definition: A token is a single word, punctuation mark, or symbol. Count tokens carefully to ensure compliance with the limit.

For each feature: Provide a concise description within the 40-token limit. Use the provided questions for guidance.

Repository information:

Repository directory tree structure: {1}
Codebase dependencies and software: {2}
Codebase file summaries: {3}

Thank you for your thorough analysis!
"""
overview = """Create a concise summary that highlights the core functionality and benefits of the code repository {0}. \
Emphasize the practical applications and unique advantages the project offers, avoiding technical jargon and specifications. \
Refrain from mentioning the project through its URL. Included are supplementary details and materials about the codebase and its elements to enhance your understanding. \

Repository information:

Repository directory tree structure: {1}
Codebase dependencies and software: {2}
Codebase file summaries: {3}

Thank you for your thorough analysis!
"""
slogan = """Devise an attention-grabbing and memorable slogan for the code repository {0}. \
Keep the slogan within 15 tokens and avoid using the project's URL or repository name. \
For instance, consider the example: "A simple, fast, and reliable package manager.
"""
summaries = """Deliver a succinct summary in no more than 50 tokens, emphasizing the main role \
and critical features of this code snippet in relation to its parent repository's architecture. \
Focus on what the code achieves, steering clear of technical implementation details. Included are \
supplementary details and materials about the codebase and its elements to enhance your understanding. \
Provided information includes:\n
- Repository layout and directory structure: {0}
- List of dependencies and software used in the codebase: {1}
- Summaries of key files within the codebase: {2}
"""
