# Model Settings
[api]
endpoint = "https://api.openai.com/v1/chat/completions"
encoding = "cl100k_base"
model = "gpt-4"
rate_limit = 5
tokens = 669
tokens_max = 7999
temperature = 1.1

# CLI Options
[cli]
emojis = true
offline = false

# Git Options
[git]
repository = "https://github.com/eli64s/readme-ai"

# Paths
[paths]
dependency_files = "dependency_files.toml"
identifiers = "identifiers.toml"
ignore_files = "ignore_files.toml"
language_names = "language_names.toml"
language_setup = "language_setup.toml"
shieldsio_icons = "data/shieldsio.json"
skill_icons = "data/skill_icons.json"
output = "readme-ai.md"

# Prompts
[prompts]
features = """Hello! Analyze the repository {0} and following the instructions below to generate a comprehensive list of features.
Please provide a comprehensive technical analysis of the codebase and its components.
Consider the codebase as a whole and highlight the key characteristics, design patterns, architectural decisions, and any other noteworthy elements.
Generate your response as a Markdown table with the following columns:

|    | Feature            | Description                                                                                                        |
|----|--------------------|--------------------------------------------------------------------------------------------------------------------|
| ‚öôÔ∏è | **Architecture**   | Analyze the structural design of the system here. Limit your response to <= 65 words.             |
| üìÑ | **Documentation**  | Discuss the quality and comprehensiveness of the documentation here. Limit your response to <= 65 words.|
| üîó | **Dependencies**   | Examine the external libraries or other systems that this system relies on here. Limit your response to <= 65 words.|
| üß© | **Modularity**     | Discuss the system's organization into smaller, interchangeable components here. Limit your response to <= 65 words.|
| üß™ | **Testing**        | Evaluate the system's testing strategies and tools here. Limit your response to <= 65 words.       |
| ‚ö°Ô∏è  | **Performance**    | Analyze how well the system performs, considering speed, efficiency, and resource usage here. Limit your response to <= 65 words.|
| üîê | **Security**       | Assess the measures the system uses to protect data and maintain functionality here. Limit your response to <= 65 words.|
| üîÄ | **Version Control**| Discuss the system's version control strategies and tools here. Limit your response to <= 65 words.|
| üîå | **Integrations**   | Evaluate how the system interacts with other systems and services here. Limit your response to <= 65 words.|
| üì∂ | **Scalability**    | Analyze the system's ability to handle growth here. Limit your response to <= 65 words.           |

Repository Details:
\nDirectory Tree: {1}\nDependencies: {2}\nCode Summaries: {3}\n
"""
overview = """Generate a <=100 word summary that describes the capabilities of the repository {0}.
Focus on the project's use-case and value proposition, not its technical details.
Do not refer to the project using the URL provided. Below are more details of the
project for you can get a deep nderstanding of the codebase and its components.
Repository Details:
\nDirectory Tree: {1}\nDependencies: {2}\nCode Summaries: {3}\n
"""
slogan = "Conceptualize a catchy and memorable slogan for the GitHub project: {0}. Limit your response to 80 characters."
summaries = """Offer a comprehensive summary <= 80 words that encapsulates the core functionalities of the code below.
Aim for precision and conciseness in your explanation, ensuring a fine balance between detail and brevity.
\nDirectory Tree: {0}\nPath: {1}\nCode:\n{2}\n
"""

# Markdown Templates
[md]
tables = ""
default = "‚ñ∫ INSERT-TEXT"
dropdown = """<details closed><summary>{}</summary>\n\n{}\n\n</details>\n"""

header = """<div align="center">
<h1 align="center">
<img src="https://raw.githubusercontent.com/PKief/vscode-material-icon-theme/ec559a9f6bfd399b82bb44393651661b08aaf7ba/icons/folder-markdown-open.svg" width="100" />
<br>{0}</h1>
<h3>‚ó¶ {1}</h3>
<h3>‚ó¶ Developed with the software and tools below.</h3>
"""

badges = """<p align="center">
{0}
</p>
<img src="https://img.shields.io/github/license/{1}?style={2}&color=5D6D7E" alt="GitHub license" />
<img src="https://img.shields.io/github/last-commit/{1}?style={2}&color=5D6D7E" alt="git-last-commit" />
<img src="https://img.shields.io/github/commit-activity/m/{1}?style={2}&color=5D6D7E" alt="GitHub commit activity" />
<img src="https://img.shields.io/github/languages/top/{1}?style={2}&color=5D6D7E" alt="GitHub top language" />
</div>
\n---
"""

badges_alt = """
<div align="center">
    <h1>{}</h1>
    <h3>‚ó¶ {}</h3>
    <h3>‚ó¶ Developed with the software and tools below.</h3>
</div>

<p align="center">
  <a href="https://skillicons.dev">
    <img src={} />
  </a>
</p>

---
"""

badges_offline = """<p align="center">
{0}
</p>
</div>
\n---
"""

badge_style="flat-square"

toc = """
## üìñ Table of Contents
- [üìñ Table of Contents](#-table-of-contents)
- [üìç Overview](#-overview)
- [üì¶ Features](#-features)
- [üìÇ repository Structure](#-repository-structure)
- [‚öôÔ∏è Modules](#modules)
- [üöÄ Getting Started](#-getting-started)
    - [üîß Installation](#-installation)
    - [ü§ñ Running {0}](#-running-{0})
    - [üß™ Tests](#-tests)
- [üõ£ Roadmap](#-roadmap)
- [ü§ù Contributing](#-contributing)
- [üìÑ License](#-license)
- [üëè Acknowledgments](#-acknowledgments)
\n---
"""

intro = """
\n## üìç Overview
\n{}
\n---
\n## üì¶ Features
\n{}
\n---
"""

tree = """
\n## üìÇ Repository Structure

```sh
{0}
```

---
"""

modules = """
\n## ‚öôÔ∏è Modules
"""
setup = """---
\n## üöÄ Getting Started

***Dependencies***

Please ensure you have the following dependencies installed on your system:
\n`- ‚ÑπÔ∏è Dependency 1`
\n`- ‚ÑπÔ∏è Dependency 2`
\n`- ‚ÑπÔ∏è ...`

### üîß Installation
\n1. Clone the {0} repository:
```sh\ngit clone {1}\n```
\n2. Change to the project directory:
```sh\ncd {0}\n```
\n3. Install the dependencies:
```sh\n{2}\n```

### ü§ñ Running {0}
\n```sh\n{3}\n```

### üß™ Tests
```sh\n{4}\n```
\n---
"""

contribute = """
\n## üõ£ Project Roadmap

> - [X] `‚ÑπÔ∏è  Task 1: Implement X`
> - [ ] `‚ÑπÔ∏è  Task 2: Implement Y`
> - [ ] `‚ÑπÔ∏è ...`

\n---

## ü§ù Contributing

Contributions are welcome! Here are several ways you can contribute:

- **[Submit Pull Requests](https://github.com/{0}/blob/main/CONTRIBUTING.md)**: Review open PRs, and submit your own PRs.
- **[Join the Discussions](https://github.com/{0}/discussions)**: Share your insights, provide feedback, or ask questions.
- **[Report Issues](https://github.com/{0}/issues)**: Submit bugs found or log feature requests for {1}.

#### *Contributing Guidelines*

<details closed>
<summary>Click to expand</summary>

1. **Fork the Repository**: Start by forking the project repository to your GitHub account.
2. **Clone Locally**: Clone the forked repository to your local machine using a Git client.
   ```sh
   git clone <your-forked-repo-url>
   ```
3. **Create a New Branch**: Always work on a new branch, giving it a descriptive name.
   ```sh
   git checkout -b new-feature-x
   ```
4. **Make Your Changes**: Develop and test your changes locally.
5. **Commit Your Changes**: Commit with a clear and concise message describing your updates.
   ```sh
   git commit -m 'Implemented new feature x.'
   ```
6. **Push to GitHub**: Push the changes to your forked repository.
   ```sh
   git push origin new-feature-x
   ```
7. **Submit a Pull Request**: Create a PR against the original project repository. Clearly describe the changes and their motivations.

Once your PR is reviewed and approved, it will be merged into the main branch.

</details>

---

## üìÑ License


This project is protected under the [SELECT-A-LICENSE](https://choosealicense.com/licenses) License. For more details, refer to the [LICENSE](https://choosealicense.com/licenses/) file.

---

## üëè Acknowledgments

- List any resources, contributors, inspiration, etc. here.

[**Return**](#Top)

---

"""
