# Model API Settings
[api]
endpoint = "https://api.openai.com/v1/chat/completions"
encoding = "cl100k_base"
model = "gpt-3.5-turbo"
rate_limit = 3
tokens = 750
tokens_max = 4000
temperature = 1.0

# CLI Options
[cli]
badges = ""
emojis = true
offline = false

# Git Options
[git]
repository = "https://github.com/eli64s/readme-ai"

# Paths
[paths]
dependency_files = "dependency_files.toml"
identifiers = "identifiers.toml"
ignore_files = "ignore_files.toml"
language_names = "language_names.toml"
language_setup = "language_setup.toml"
shieldsio_icons = "data/shieldsio.json"
app_icons = "data/apps.json"
output = "readme-ai.md"

# Prompts
[prompts]
features = """Hello! Analyze the repository {0} and following the instructions below to generate a comprehensive list of features.
Please provide a comprehensive technical analysis of the codebase and its components.
Consider the codebase as a whole and highlight the key characteristics, design patterns, architectural decisions, and any other noteworthy elements.
Generate your response as a Markdown table with the following columns:

|    | Feature            | Description                                                                                                        |
|----|--------------------|--------------------------------------------------------------------------------------------------------------------|
| âš™ï¸ | **Architecture**   | Analyze the structural design of the system here. Limit your response to a maximum of 200 characters.             |
| ğŸ“„ | **Documentation**  | Discuss the quality and comprehensiveness of the documentation here. Limit your response to a maximum of 200 characters.|
| ğŸ”— | **Dependencies**   | Examine the external libraries or other systems that this system relies on here. Limit your response to a maximum of 200 characters.|
| ğŸ§© | **Modularity**     | Discuss the system's organization into smaller, interchangeable components here. Limit your response to a maximum of 200 characters.|
| ğŸ§ª | **Testing**        | Evaluate the system's testing strategies and tools here. Limit your response to a maximum of 200 characters.       |
| âš¡ï¸  | **Performance**    | Analyze how well the system performs, considering speed, efficiency, and resource usage here. Limit your response to a maximum of 200 characters.|
| ğŸ” | **Security**       | Assess the measures the system uses to protect data and maintain functionality here. Limit your response to a maximum of 200 characters.|
| ğŸ”€ | **Version Control**| Discuss the system's version control strategies and tools here. Limit your response to a maximum of 200 characters.|
| ğŸ”Œ | **Integrations**   | Evaluate how the system interacts with other systems and services here. Limit your response to a maximum of 200 characters.|
| ğŸ“¶ | **Scalability**    | Analyze the system's ability to handle growth here. Limit your response to a maximum of 200 characters.           |

Repository Details:
\nDirectory Tree: {1}\nDependencies: {2}\nCode Summaries: {3}\n
"""
overview = """Generate a <=100 word summary that describes the capabilities of the repository {0}.
Focus on the project's use-case and value proposition, not its technical details.
Do not refer to the project using the URL provided. Below are more details of the
project for you can get a deep nderstanding of the codebase and its components.
Repository Details:
\nDirectory Tree: {1}\nDependencies: {2}\nCode Summaries: {3}\n
"""
slogan = "Conceptualize a catchy and memorable slogan for the GitHub project: {0}. Limit your response to 80 characters."
summaries = """Offer a comprehensive summary <= 80 words that encapsulates the core functionalities of the code below.
Aim for precision and conciseness in your explanation, ensuring a fine balance between detail and brevity.
\nDirectory Tree: {0}\nPath: {1}\nCode:\n{2}\n
"""

# Markdown Templates
[md]
tables = ""
default = "â–º INSERT-TEXT"
dropdown = """<details closed><summary>{}</summary>\n\n{}\n\n</details>\n"""

header = """<div align="center">
<h1 align="center">
<img src="https://raw.githubusercontent.com/PKief/vscode-material-icon-theme/ec559a9f6bfd399b82bb44393651661b08aaf7ba/icons/folder-markdown-open.svg" width="100" />
<br>{0}</h1>
<h3>â—¦ {1}</h3>
<h3>â—¦ Developed with the software and tools below.</h3>
"""

badges = """<p align="center">
{0}
</p>
<img src="https://img.shields.io/github/license/{1}?style={2}&color=5D6D7E" alt="GitHub license" />
<img src="https://img.shields.io/github/last-commit/{1}?style={2}&color=5D6D7E" alt="git-last-commit" />
<img src="https://img.shields.io/github/commit-activity/m/{1}?style={2}&color=5D6D7E" alt="GitHub commit activity" />
<img src="https://img.shields.io/github/languages/top/{1}?style={2}&color=5D6D7E" alt="GitHub top language" />
</div>
\n---
"""

badges_alt = """
<div align="center">
    <h1>{}</h1>
    <h3>â—¦ {}</h3>
    <h3>â—¦ Developed with the software and tools below.</h3>
</div>

<p align="center">
  <a href="https://skillicons.dev">
    <img src={} />
  </a>
</p>

---
"""

badges_offline = """<p align="center">
{0}
</p>
</div>
\n---
"""

toc = """
## ğŸ“– Table of Contents
- [ğŸ“– Table of Contents](#-table-of-contents)
- [ğŸ“ Overview](#-overview)
- [ğŸ“¦ Features](#-features)
- [ğŸ“‚ repository Structure](#-repository-structure)
- [âš™ï¸ Modules](#modules)
- [ğŸš€ Getting Started](#-getting-started)
    - [ğŸ”§ Installation](#-installation)
    - [ğŸ¤– Running {0}](#-running-{0})
    - [ğŸ§ª Tests](#-tests)
- [ğŸ›£ Roadmap](#-roadmap)
- [ğŸ¤ Contributing](#-contributing)
- [ğŸ“„ License](#-license)
- [ğŸ‘ Acknowledgments](#-acknowledgments)
\n---
"""

intro = """
\n## ğŸ“ Overview
\n{}
\n---
\n## ğŸ“¦ Features
\n{}
\n---
"""

tree = """
\n## ğŸ“‚ Repository Structure

```sh
{0}
```

---
"""

modules = """
\n## âš™ï¸ Modules
"""
setup = """---
\n## ğŸš€ Getting Started

***Dependencies***

Please ensure you have the following dependencies installed on your system:
\n`- â„¹ï¸ Dependency 1`
\n`- â„¹ï¸ Dependency 2`
\n`- â„¹ï¸ ...`

### ğŸ”§ Installation
\n1. Clone the {0} repository:
```sh\ngit clone {1}\n```
\n2. Change to the project directory:
```sh\ncd {0}\n```
\n3. Install the dependencies:
```sh\n{2}\n```

### ğŸ¤– Running {0}
\n```sh\n{3}\n```

### ğŸ§ª Tests
```sh\n{4}\n```
\n---
"""

ending = """
\n## ğŸ›£ Project Roadmap

> - [X] `â„¹ï¸  Task 1: Implement X`
> - [ ] `â„¹ï¸  Task 2: Implement Y`
> - [ ] `â„¹ï¸ ...`

\n---

## ğŸ¤ Contributing

[**Discussions**](https://github.com/{0}/discussions)
  - Join the discussion here.

[**New Issue**](https://github.com/{0}/issues)
  - Report a bug or request a feature here.

[**Contributing Guidelines**](https://github.com/{0}/blob/main/CONTRIBUTING.md)

- Contributions are welcome! Please follow these steps:

1. Fork the project repository to your GitHub account.
2. Clone the forked repository to your local machine using a Git client like Git or GitHub Desktop.
3. Create a new branch with a descriptive such as `new-feature-x` or `bugfix-issue-x`.
```sh
git checkout -b new-feature-x
```
4. Develop your changes locally.
5. Commit your updates with a clear explanation of the changes you've made.
```sh
git commit -m 'Implemented new feature.'
```
6. Push your changes to your forked repository on GitHub.
```sh
git push origin new-feature-x
```
7. Create a new pull request to the original project repository. In the pull request, describe the changes you've made and why they're necessary.
8. Once your pull request is reviewed, it will be merged into the main branch of the project repository.

---

## ğŸ“„ License


This project is protected under the [SELECT-A-LICENSE](https://choosealicense.com/licenses) License. For more details, refer to the [LICENSE](https://choosealicense.com/licenses/) file.

---

## ğŸ‘ Acknowledgments

- List any resources, contributors, inspiration, etc. here.

[**Return**](#Top)

---

"""
